#!/usr/bin/env python3

import os
import shapefile
import sys

def main():
    with shapefile.Writer('test_files/null') as w:
        w.field('name', 'C')
        w.null()
        w.record('a')
        w.null()
        w.record('b')
    with shapefile.Writer('test_files/point') as w:
        w.field('name', 'C')
        w.point(10, 20)
        w.record('a')
        w.point(50, 40)
        w.record('b')
    with shapefile.Writer('test_files/multipoint') as w:
        w.field('name', 'C')
        w.multipoint([
            [0, 0],
            [10, 10],
            [20, 10],
            [5, 5],
        ])
        w.record('a')
        w.multipoint([
            [0, 0],
            [4, 5]
        ])
        w.record('b')
    with shapefile.Writer('test_files/polyline') as w:
        w.field('name', 'C')
        w.line([
            [[12, 56], [70, 90], [0, 0]],
            [[45, 6], [89.3, 12.2]]
        ])
        w.record('a')
        w.line([
            [[0, 0], [42.42, 66.66]]
        ])
        w.record('b')
    with shapefile.Writer('test_files/polygon') as w:
        w.field('name', 'C')
        w.poly([
            [[0, 0], [0, 5], [5, 5], [5, 0], [0, 0]],
            [[1, 1], [1, 4], [4, 4], [4, 1], [1, 1]]
        ])
        w.record('a')
        w.poly([
            [[0, 0], [5, 5], [5, 0], [0, 0]]
        ])
        w.record('b')
    with shapefile.Writer('test_files/pointm') as w:
        w.field('name', 'C')
        w.pointm(0, 0, 100.0)
        w.record('a')
        w.pointm(42.2, 55.5, 50.0)
        w.record('b')
        w.pointm(20.3, 30.0)
        w.record('c')
    with shapefile.Writer('test_files/multipointm') as w:
        w.field('name', 'C')
        w.multipointm([
            [0.0, 0.0, 4.0],
            [1.0, 2.0, 8.0],
            [3.0, 5.0, None]
        ])
        w.record('a')
        w.multipointm([
            [0.0, 1.0, 100.0]
        ])
        w.record('b')
    with shapefile.Writer('test_files/polylinem') as w:
        w.field('name', 'C')
        w.linem([
            [[12, 56, 10.0], [70, 90, 11.0], [0, 0, 12.0]],
            [[45, 6], [89.3, 12.2, None]]
        ])
        w.record('a')
        w.linem([
            [[0, 0, 4.0], [42.42, 66.66, 5.0]]
        ])
        w.record('b')
    with shapefile.Writer('test_files/polygonm') as w:
        w.field('name', 'C')
        w.polym([
            [[0, 0, 1.0], [0, 5, 2.0], [5, 5, 3.0], [5, 0, 4.0], [0, 0, 5.0]],
            [[1, 1, None], [1, 4, 1.0], [4, 4, None], [4, 1, 2.0], [1, 1, None]]
        ])
        w.record('a')
        w.polym([
            [[0, 0, 100.0], [5, 5, 200.0], [5, 0, 300.0], [0, 0, 400.1]]
        ])
        w.record('b')
    with shapefile.Writer('test_files/pointz') as w:
        w.field('name', 'C')
        w.pointz(0, 0, 0, 100.0)
        w.record('a')
        w.pointz(10, 20, 30)
        w.record('b')
    with shapefile.Writer('test_files/multipointz') as w:
        w.field('name', 'C')
        w.multipointz([
            [0, 0, 0, 100.0],
            [10, 10, 1, 200.0],
            [20, 10, 2, None],
            [5, 5, 3, 400.0],
        ])
        w.record('a')
        w.multipointz([
            [0, 0, 0, 12.2],
            [4, 5, 6, 13.3]
        ])
        w.record('b')
    with shapefile.Writer('test_files/polylinez') as w:
        w.field('name', 'C')
        w.linez([
            [[12, 56, 11.1, 10.0], [70, 90, 22.2, 11.0], [0, 0, 33.3, 12.0]],
            [[45, 6, 44.4], [89.3, 12.2, 55.5, None]]
        ])
        w.record('a')
        w.linez([
            [[0, 0, 66.6, 4.0], [42.42, 66.66, 77.7, 5.0]]
        ])
        w.record('b')

if __name__ == '__main__':
    sys.exit(main())